//PERSONAL INFORMATION
var finame = "Shameer";
var lname = "Ahmed";
console.log(finame + " " + lname);
var fatherfname = "Shafiq";
var fatherlname = "Ahmed";
console.log(fatherfname + " " + fatherlname);
var age = 15;
console.log(age);
var email = "shoaib2010a@aptechgdn.net";
console.log(email);
var phone = 923128878543;
console.log(phone);
var religion = "Islam";
console.log(religion);
var nationality = "Pakistani";
console.log(nationality);
var isStudent = true;
console.log(isStudent);
var isEmployed = false;
console.log(isEmployed);
var Qualification = "Matric";
console.log(Qualification);
var Hobby = "create new programs";
console.log(Hobby);
var MyGoal = "I will go to perform Umraah with my Family";
//Adress
var Adress = "H.# C5/99 Old Golimaar";
console.log(Adress);
var Area = "Asif colony";
console.log(Area);
var City = "Karachi";
console.log(City);
